### ISSUE TITLE
aws Cognito JWT Token claim 'cognito:groups' tranform to  claim 'groups'

### ISSUE THREAD

**Issue by aerodc** [smallrye/smallrye-jwt#105]
Hello Guys,

Do you know how to tell smallrye-jwt to use claim 'cognito:groups' as standard claim 'groups'?

Thanks a lot

**Comment by sberyozkin** [comment]
Can you type a sample JWT JSON please ?

**Comment by aerodc** [comment]
@sberyozkin thanks for your quick response, 
the sample JWT Json is aws cognito jwt token like:
````
{
  "sub": "bbbbbbbb",
  "aud": "xxxxx",
  "cognito:groups": [
    "group1"
  ],
  "email_verified": true,
  "event_id": "ccccccccc",
  "token_use": "id",
  "auth_time": 1563193576,
  "iss": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-CCCCC",
  "cognito:username": "tester",
  "exp": 12233444,
  "iat": 12233444,
  "email": "test@gmail.com"
}

**Comment by sberyozkin** [comment]
@aerodc sure see [this property](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L170). Can you confirm it works please ?

**Comment by aerodc** [comment]
@sberyozkin 
should I put it like this? 
````
smallrye.jwt.path.groups=payload/'cognito:groups'

````
but I got errors message 
````
No claim exists at the path payload/'cognito:groups' at segment payload
Claim value at the path payload/'cognito:groups' is not an array

**Comment by sberyozkin** [comment]
@aerodc just 
```
smallrye.jwt.path.groups=cognito:groups'
```

**Comment by sberyozkin** [comment]
@aerodc np, thanks for your question. Please consider asking at the Smallrye [forum](https://groups.google.com/forum/#!forum/smallrye) or at the Quarkus/Thorntail lists if you work with either of these projects
