### ISSUE TITLE
Claim CDI producer methods missing @RequestScoped

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-jwt#113]
I didn't notice this before because I was directly using `JsonWebToken`s, but the producer methods in `ClaimValueProducer`, `JsonValueProducer`, and `RawClaimTypeProducer` do not specify a scope, which defaults to `@Dependent`. When injecting into `@ApplicationScoped` JAX-RS resources (and also `@Stateless` resources), the claims are not updated per each request.

**Comment by sberyozkin** [comment]
Returning null with the request scoped methods will require a [custom proxy](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/auth/cdi/PrincipalProducer.java#L52), will it work for individual claims ?

**Comment by MikeEdgar** [comment]
I think it will not work for individual claims or those inside of `Optional`.

**Comment by sberyozkin** [comment]
OK, please experiment.

**Comment by sberyozkin** [comment]
Will check myself as well with in Thorntail

**Comment by MikeEdgar** [comment]
I take back what I said about the JSON types. This may only be possible with `ClaimValue`, which I think is fine.

**Comment by mkouba** [comment]
@sberyozkin Yes, only `@Dependent` producer methods are allowed to return `null`. For normal scopes you would get an `IllegalProductException`.

**Comment by sberyozkin** [comment]
@mkouba yes, thanks for the confirmation, I recall having to deal with it when updating PrincipalProducer  :-)
