### ISSUE TITLE
Are JWKS files cached locally?

### ISSUE THREAD

**Issue by aesteve** [smallrye/smallrye-jwt#118]
Hello and thank you for your work.

I've introduced smallrye-jwt into my application and faced an SSL issue when the first request hit the secured endpoint.

So I'm guessing fetching JWKS from a remote location is lazy. Fine.

Is this put in a cache though ? I'm really concerned about this, since it could really slow down the incoming traffic dramatically, or even fail if JWKS endpoint is down for a moment.

I tried to look [here](https://github.com/smallrye/smallrye-jwt/blob/6a9ed997232319c043bbb3ccb7adfe2d6dde5af6/implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java#L122) but I'm not 100% sure.

Could you please confirm and close this issue/question if you have a few minutes? That'd be really helpful. 

Thank you.

**Comment by sberyozkin** [comment]
Hi @aesteve 
The [HttpsJwksVerificationKeyResolver](https://bitbucket.org/b_c/jose4j/src/master/src/main/java/org/jose4j/keys/resolvers/HttpsJwksVerificationKeyResolver.java) uses [HttpsJwks](https://bitbucket.org/b_c/jose4j/src/master/src/main/java/org/jose4j/jwk/HttpsJwks.java) so yes the cache is used.
Thanks

**Comment by aesteve** [comment]
Perfect!
Thanks a lot.
