### ISSUE TITLE
Improve the CDI code

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#132]
Right now Thorntail and Quarkus have some CDI code which ideally should be located in smallrye-jwt in the form of `CDIUtils` and may be `AbstractExtension` referring to these `CDIUtils` for Thorntail (and may be WildFly) CDI extension code, as well as any Quarkus code integrating smallrye-jwt be able to reuse the same code.

**Comment by kenfinnigan** [comment]
Bear in mind we want to try and do things that don't require a CDI Extension to do what is needed
