### ISSUE TITLE
Allow unverified JWT

### ISSUE THREAD

**Issue by FreifeldRoyi** [smallrye/smallrye-jwt#144]
Hi,
I [asked in MP-JWT github](https://github.com/eclipse/microprofile-jwt-auth/issues/132) about a way to configure `no verification` for the JWT. It might be something proprietary so I'll try asking here too. Is it possible to inject an un-verified JWT? I had to manually parse (and verify the auth header) instead of just using `@Inject` like I think should be possible.

**Comment by sberyozkin** [comment]
@FreifeldRoyi What I can suggest is to register a custom [JWTCallerPrincipalFactory](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipalFactory.java), similarly to the way [it is done](https://github.com/thorntail/thorntail/blob/master/fractions/keycloak-microprofile-jwt/src/main/java/org/wildfly/swarm/keycloak/mpjwt/deployment/KeycloakJWTCallerPrincipalFactory.java) for the Thorntail Keycloak integration. There you'd just parse the token with Jose4J and use `DefaultJWTCallerPrincipal`.
Let me know how it goes please

**Comment by sberyozkin** [comment]
@FreifeldRoyi if we update `smallrye-jwt` to allow for the unverified tokens then it won't pass any security review, even though it would be done with some configuration, and as in your case, you can be assured enough that it won't be a problem. So I'll close this issue, but I'll wait till you confirm the customization works in principle for you

**Comment by FreifeldRoyi** [comment]
Is there any preference doing that instead of implementing a parser in Jax-rs filter and adding to request context?

**Comment by sberyozkin** [comment]
@FreifeldRoyi No, not really, if all you need is to use MP JWT API, then indeed just convert it into `JsonWebToken` and set it as a new (JAX-RS) security context

**Comment by omgbanana** [comment]
Hello!

There was a whole conversation about this (https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/MP-JWT.20validation.20skip). The thing is at some point You do not need to verify the token, but You still want to get the roles out of it and use the quarkus-jwt for authorization purposes.

It makes it hard to use in bigger solutions that have the validation done before it reaches the quarkus application (part of the whole cluster-eco-system). 

Would injecting JWTCallerPrincipalFactory make it possible for me to extract the roles from the un-verified token and inject them into the quarkus security principal used for role matching? (I tried it briefly and I could not find a way to inject it). Is there a solution that is not too hacky-slashy in the global view of software development? One that can be reused in all microservices of the eco-system that is not copy paste this solution manually and override the default implementation?

I was wondering if this is going to live, or get discarded. It is quite important for me to know.

**Comment by sberyozkin** [comment]
@omgbanana this is why I'm keeping this issue open :-). Custom factory path should be good enough but it requires a bit more thinking how to do it right, I'll try to prioritize on it soon

**Comment by andreas-eberle** [comment]
For those looking for the code of how to get an unverified `JsonWebToken` object from the token string, this code should do the trick:

```
    public JsonWebToken decodeTokenUnverified(String tokenString) throws InvalidJwtException {
        JwtConsumer consumer = new JwtConsumerBuilder()
                .setSkipAllValidators()
                .setDisableRequireSignature()
                .setSkipSignatureVerification()
                .build();

        JwtClaims claimsSet = consumer.processToClaims(tokenString);
        return new DefaultJWTCallerPrincipal(tokenString, claimsSet);
    }
```

**Comment by omgbanana** [comment]
> For those looking for the code of how to get an unverified `JsonWebToken` object from the token string, this code should do the trick:
> 
> ```
>     public JsonWebToken decodeTokenUnverified(String tokenString) throws InvalidJwtException {
>         JwtConsumer consumer = new JwtConsumerBuilder()
>                 .setSkipAllValidators()
>                 .setDisableRequireSignature()
>                 .setSkipSignatureVerification()
>                 .build();
> 
>         JwtClaims claimsSet = consumer.processToClaims(tokenString);
>         return new DefaultJWTCallerPrincipal(tokenString, claimsSet);
>     }
> ```

And how will this inject it into the quarkus-smallrye security context for authorization?

**Comment by andreas-eberle** [comment]
It won't. There currently does not seem to be an option to skip verification (afaik). Just wanted to share this code on how to get a JWT parsed, since I also first had to find a way to do it and thought it might help you, although it doesn't solve your problem.

**Comment by radcortez** [comment]
The factory solution should work.

Unfortunately, it seems that Quarkus instantiates the `DefaultJWTTokenParser` directly, instead of using the factory:
https://github.com/quarkusio/quarkus/commit/08777bbe4cd3700bbad19c4d1e4984c8112d664d#diff-4dabe1f5911b23eb33fd6188eefe39c2

@sberyozkin what do you think?

**Comment by sberyozkin** [comment]
It now (on master) deals with the injected `JWTParser`.
Once #194 is merged it will all work

**Comment by sberyozkin** [comment]
See the documentation, `Custom Factories`, how to inject custom factories which will bypass the verification,
https://github.com/smallrye/smallrye-jwt/blob/master/doc/modules/ROOT/pages/configuration.adoc
