### ISSUE TITLE
Add a maximum time to live property

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#146]
The tokens have to be short-lived in general, this is why, in OIDC/OAuth2 flows, refresh tokens with the longer life span exist, to refresh the ATs and thus minimize the theft risk.

JWT has an expiry claim but it may be set for a long time in the future. Sometimes to simplify the client code issuing the tokens. As such there has to be a property which can block the tokens which have been around for too long

**Comment by sberyozkin** [comment]
@MikeEdgar Hi Mike, if you can find an hour or so, can you please do a small PR for this issue ? (`ttl` property which if set would block the tokens with the longer `exp` value). I'd like to send a committer nomination and it would help if there was some recent PR.

**Comment by MikeEdgar** [comment]
@sberyozkin - I'll try to take a look at this soon.

**Comment by sberyozkin** [comment]
@MikeEdgar Thanks; your earlier contributions have been of major help, so that would've been enough as far as the committer status is concerned :-), but if you can get another PR done that would be quite perfect, cheers

**Comment by MikeEdgar** [comment]
@sberyozkin - after taking a small look at this, it seems to me that by specifying a TTL limit, the user is requiring that `exp` - `iat` <= TTL. Is that the intent (versus `exp` - current time)? If so, that seems to imply that in those cases the `iat` is a required claim.
