### ISSUE TITLE
smallrye.jwt.path.groups and smallrye.jwt.path.sub does not work with namespaced keys containing "/"

### ISSUE THREAD

**Issue by spbolton** [smallrye/smallrye-jwt#164]
Auth0  does not automatically add the sub and groups claims but custom claims can be added.   https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims  Following OIDC specification that advises ensuring custom claims are made globally unique they added a hard requirement that  custom claims to be created with a URI based namespace.  Unfortunately this means that the custom claim for groups and sub if added will always contain a "/" character.  e.g. claim could be "http://mydomain.com/groups" . The code in DefaultJWTTokenParser to find groups based upon the  smallrye.jwt.path.groups  configuration will always split the key value specified as separate path elements and there is currently no way to escape the "/" in these path configuration values with a simple string split.

private List<String> findGroups(JWTAuthContextInfo authContextInfo, JwtClaims claimsSet) {
        if (authContextInfo.getGroupsPath() != null) {
            final String[] pathSegments = authContextInfo.getGroupsPath().split("/");

Options are 
1 - to allow for escaping of / in configuration parameter to split correctly,  
2 - allow for absolute specification of claim key or 
3 - add customization of namespace prefix that will be stripped off claim key before being processed. 
4 - Ability to configure a different separator for the path configuration,  this may get confusing with the smallrye.jwt.groups-separator  configuration used for the group value.  

If a decision is made on the way forward I am happy to have a go implementing this.

**Comment by sberyozkin** [comment]
@spbolton Hi, option 1 seems simplest and most practical. I'm presuming you mean it can become a regular expression. Please have a look if you can find some time. thanks

**Comment by sberyozkin** [comment]
@spbolton Hi, if you have some time then please go ahead with a small PR, I propose to follow your step 1 idea, but simply use the double quotes for the claim names containing the forward slashes.
I'd like to have a fix for it going in in the next release due to next week, so let me know please if you have some time for it.

**Comment by sberyozkin** [comment]
@spbolton I have something nearly ready for `quarkus-oidc`, so I may as well create a PR for smallrye-jwt. Will CC you

**Comment by sberyozkin** [comment]
@MikeEdgar FYI, since you've mentioned the namespace-qualified claims in the MP JWT issue
