### ISSUE TITLE
Mike Edgar - committer nomination

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#177]
@MikeEdgar - Hi Mike, can you please give me a favor and confirm here if you accept your successful committer nomination ? I'm sorry I could not find any other way to contact you :-).

This issue will be closed once you reply.

CC @kenfinnigan

**Comment by MikeEdgar** [comment]
@sberyozkin - I accept.

**Comment by sberyozkin** [comment]
@MikeEdgar - Thanks
