### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by vankofalcon** [smallrye/smallrye-jwt#184]
Where is the project documentation? I can't find it on the official web site like the messaging docs https://smallrye.io/smallrye-reactive-messaging/
Where I can find the full list of configuration options?

**Comment by sberyozkin** [comment]
@vankofalcon I agree, but let me close this issue as a duplicate of #106.

I will get the configuration properties documented for the next release

**Comment by sberyozkin** [comment]
@vankofalcon Most of the properties are listed [here](https://quarkus.io/guides/security-jwt#additional-smallrye-jwt-configuration). But they will be documented here as well...
