### ISSUE TITLE
Cookie name property should default to MPJWT

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#188]
The spec recommends recognizing `MPJWT` name. Thus if the header property is set to `Cookie` then `MPJWT` cookie will be checked by default

**Comment by sberyozkin** [comment]
Right now it is defaulted to `Bearer`. We need to decide if we should keep it or use an opportunity (move to `2.1.0`) and replace with `MPJWT` or simply check both `Bearer` and `MPJWT` cookie names :-). The last or 2nd options look good to me.
CC @MikeEdgar @darranl

**Comment by MikeEdgar** [comment]
@sberyozkin - which version of the spec are you referring to? I didn't see that recommendation in the current PDF or the asciidoc on `master`.

**Comment by sberyozkin** [comment]
@MikeEdgar Oh, I was looking at Scott's PR. The section related to the cookies has been reverted by David:
https://github.com/eclipse/microprofile-jwt-auth/commit/96cfcd0bd4b4a280388a1e0e20987965a654c708

**Comment by sberyozkin** [comment]
Let me close this one for now
