### ISSUE TITLE
Why is JWTCallerPrincipalFactory not injected into DefaultJWTParser

### ISSUE THREAD

**Issue by andreas-eberle** [smallrye/smallrye-jwt#193]
In `DefaultJWTParser`, one field (`JWTAuthContextInfo authContextInfo`) is injected, but the other (`JWTCallerPrincipalFactory callerPrincipalFactory`) isn't. The `callerPrincipalFactory` is generated via reflection code in the `JWTCallerPrincipalFactory.instance()` method (see https://github.com/smallrye/smallrye-jwt/blob/08970ef586acb9414f0ebfcdb3fc8566e28b22cc/implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java#L46).

If there is no special reason for this behavior, I think both should be injected the same way. The current implementation makes it hard to switch out the implementation with an own implementation which requires injection.

**Comment by sberyozkin** [comment]
@andreas-eberle I think this issue is invalid. factory is the first point of entry

**Comment by andreas-eberle** [comment]
Sure, when using this library in a non CDI environment. However, if you use it with CDI, you cannot inject a different `JWTCallerPrincipalFactory` into `DefaultJWTParser` if your implementaton requires injection. Is there a good way to combine both?

**Comment by sberyozkin** [comment]
But it is the wrong relationship. The parser is not supposed to know what the factory is

**Comment by andreas-eberle** [comment]
I don't understand your argument. In the current code the `DefaultJWTParser` knows more about the factory than in my proposed changes. 

To clarify: In the current code, the `DefaultJWTParser`
* Gets injected the `JWTAuthContextInfo` => a dependency injection framework is required to be able to use the `DefaultJWTParser` or the `JWTAuthContextInfo` has to be injected manually via the new constructor.
* In contrast, the instance of the `JWTCallerPrincipalFactory` is lazily created by the `DefaultJWTParser` with the `JWTCallerPrincipalFactory.instance()` method. It seems weired to me to use two different ways of doing the same in one class. 

I understand the usefulness of `JWTCallerPrincipalFactory.instance()` when simply using the library to parse a JWT. However, when using the `DefaultJWTParser`, I cannot fully control/configure the dependencies of this class via one single mechanism.

In the proposed changes of #194:
* `DefaultJWTParser` is changed to get the `JWTCallerPrincipalFactory` (which is the abstract base class) via dependency injection instead of the propretary `JWTCallerPrincipalFactory.instance()` method. 
* The `@ApplicationScoped` annotation is added to `DefaultJWTCallerPrincipalFactory`, which is the default implementation of `JWTCallerPrincipalFactory` in this library. 

All in all, with the proposed changes, I can now use standard dependency injection to fully configure the `DefaultJWTParser` as well as mock all its dependencies via constructor injection in tests. Nothing more is changed and the default behavior is still the same. Only a single `DefaultJWTCallerPrincipalFactory` is created and the using code will be able to inject it, since dependency injection must already be used to build `DefaultJWTParser` in the first place. 

I hope I was able to make my intentions more understandable. I really do think this PR offers a benefit of configurability + testability while not changing the current behavior and requirements for code using this library.

**Comment by andreas-eberle** [comment]
@sberyozkin: Can you found the time to elaborate more on your thoughts on this topic?

**Comment by sberyozkin** [comment]
@andreas-eberle Sorry for a delay. Looking more carefully into your PR...
