### ISSUE TITLE
Stabilize TCK test runs

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#204]
@radcortez, I'm just opening the issue because it failed with another PR,
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project smallrye-jwt-tck: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/runner/smallrye-jwt/testsuite/tck/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/runner/smallrye-jwt/testsuite/tck && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/runner/smallrye-jwt/testsuite/tck/target/jacoco.exec,append=true -jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire/surefirebooter6991556427656949701.jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire 2020-03-20T16-22-07_975-jvmRun1 surefire2144571742854082885tmp surefire_23023401477214946234tmp
[ERROR] Process Exit Code: 0
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/runner/smallrye-jwt/testsuite/tck && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/runner/smallrye-jwt/testsuite/tck/target/jacoco.exec,append=true -jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire/surefirebooter6991556427656949701.jar /home/runner/smallrye-jwt/testsuite/tck/target/surefire 2020-03-20T16-22-07_975-jvmRun1 surefire2144571742854082885tmp surefire_23023401477214946234tmp
[ERROR] Process Exit Code: 0
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
...
```
May be something needs to be adjusted to align ii with the way `smallrye-config` TCK runs for example ? 
I'll rebuild another PR in meantime, next week would be fine, enjoy the weekends :-)

**Comment by radcortez** [comment]
The VM is just crashing on Semaphore. Not sure why... It is strange because in the original TCK PR it run without any issue.

In Github Actions, everything seems to be building ok:
https://github.com/smallrye/smallrye-jwt/actions

**Comment by sberyozkin** [comment]
@radcortez the PR itself is good, it did not crash the 2nd time, so looks like something is not stable in semaphore. I've checked semaphore/smallrye-config and see no difference in the way it is set up...

**Comment by radcortez** [comment]
Yes, we had similar issues with Semaphore in the past. We are not sure what causes this, but it is not a configuration issue.

**Comment by sberyozkin** [comment]
@radcortez Sure, looks like `semaphore/smallrye-jwt` space needs to adapt to the new test requirements :-)

**Comment by radcortez** [comment]
Well hopefully, we will drop Semaphore and just use GH Actions :)

**Comment by radcortez** [comment]
Actually , I think we can do that move. We completely drop Semaphore in SmallRye Config. I think the project is Semaphore is still active but I will shut it down today.

**Comment by radcortez** [comment]
I have no idea why Semaphore sometimes build properly and some other times just fails. The issue is with a JVM crash. I suspect to be related with the JVM version, since it is using a really old version of JDK 8 (8u181) and there is no way to update it.

I think we can disable the TCK in Semaphore (and still get the result run from GH Actions) with #208, until we completely transition to GH Actions.

**Comment by radcortez** [comment]
I also suggest to switch the status check in the project configuration from Semaphore to GH Actions. I can do it, but I don't want to do it without your knowledge @sberyozkin :)

**Comment by sberyozkin** [comment]
@radcortez sorry, has been side-tracked a bit. It all sounds good, Just to clarify, before the transition is complete, I'll still be able to release the next smallrye-jwt via  the semaphore ?

**Comment by radcortez** [comment]
With https://github.com/smallrye/smallrye-jwt/pull/208 yes.

The only issue is when Semaphore VM randomly crashes with the TCK. By removing the TCK run from Semaphore (but still relying on GH Actions to report the run), we should be ok.
