### ISSUE TITLE
"exp" claim implementation not compliant with RFC7519

### ISSUE THREAD

**Issue by moyshe** [smallrye/smallrye-jwt#215]
According to RFC7519's chapter 4.1.4., "exp" field is optional in JWT. In Smallrye implementation if the claim is missing token is considered invalid. It would be nice to have an ability to configure how the library behaves. ATM, I can see in the code some hints, that it's impossible to skip "exp" validation:
```
public JwtConsumerBuilder setRequireExpirationTime() 
{
    dateClaimsValidator.setRequireExp(true);
    return this;
}
```
```
public class DefaultJWTTokenParser {
    (...)
    public JwtContext parse(final String token, final JWTAuthContextInfo authContextInfo) throws ParseException {
        try {
            JwtConsumerBuilder builder = new JwtConsumerBuilder()
                    .setRequireExpirationTime();
    (...)
```
One of available solutions can be found right underneath the code above:
```
            if (authContextInfo.getMaxTimeToLiveSecs() != null) {
                builder.setRequireIssuedAt();
            }
```
The `NumericDateValidator` class in `jose4j` seems to be already prepared for handling "exp" properly. It's only a matter of setting the `requireExp` flag:
```
    @Override
    public Error validate(JwtContext jwtContext) throws MalformedClaimException
    {
        (...)
        if (requireExp && expirationTime == null)
        {
            return MISSING_EXP;
        }
        (...)
```

**Comment by sberyozkin** [comment]
@moyshe I think this issue has been discussed before. RFC7519 is a general purpose spec, MP JWT is built around it and has different requirements - we don't want to open an option for unlimited tokens be used.
Why would a token in your case have no `exp` claim ? Any OIDC/OAuth2 provider I can think of will put it in the token, and it is strightforward to add it to the token even if the token is self-issued.

**Comment by sberyozkin** [comment]
You can set it some very distant value, max long if it is of no concern in your case (though smallrye-jwt can optionally restrict now such tokens too but only optionally)

**Comment by moyshe** [comment]
I'm currently dealing with provider that aims to be 100% compliant with RFC, hence the question. I understand your point of view and don't want to push you. I just wanted to check whether it's an overlook or a conscious decision.

**Comment by sberyozkin** [comment]
Hi @moyshe but that RFC makes all the claims optional as far as I recall :-), except for a few

**Comment by sberyozkin** [comment]
@moyshe I was wrong, all of the registered claims at https://tools.ietf.org/html/rfc7519#section-4.1 are optional :-), including an issuer, audience, issued at. The question - is there any technical reason behind omitting `exp` ? If the only reason it is omitted just because the text says it is optional then IMHO this provider should instead add it

**Comment by moyshe** [comment]
I fully agree, but then why is there a way to skip issuer verification?
```
            if (authContextInfo.isRequireIssuer()) {
                builder.setExpectedIssuer(true, authContextInfo.getIssuedBy());
            } else {
                builder.setExpectedIssuer(false, null);
            }
```

**Comment by sberyozkin** [comment]
@moyshe This is a legacy code, there were some discussions at the MP JWT to support skipping the issue validation and the code (which was still in Thorntail at a time) was prototyped around it. But MP JWT does require an issuer be present. I should probably deprecate this option, similarly to the `exp`, I can't imagine why would the issuer would not bet set.

**Comment by sberyozkin** [comment]
We don't document this property (skipping the issuer) by the way

**Comment by moyshe** [comment]
Ok. As I said, I don't want to push you to anything, so I'll drop the issue. I appreciate the discussion though, thanks. Best regards!

**Comment by sberyozkin** [comment]
@moyshe Thanks, and no problems at all, it is OK for the users to argue in favour of their proposals :-)
