### ISSUE TITLE
Documentation for the property smallrye.jwt.encrypt.key-location

### ISSUE THREAD

**Issue by bobbyphilip** [smallrye/smallrye-jwt#221]
I see this property being described in the Quarkus project, but dont see it being documented here.
Is this a standard property for smallrye-jwt?

**Comment by radcortez** [comment]
Hi @bobbyphilip thanks for the heads up.

Yes, you can find them in `JwtEncryption` and `JwtSignature`. But, yes we need to document them in our docs as well.
