### ISSUE TITLE
Consistent Injection combinations of Claims

### ISSUE THREAD

**Issue by radcortez** [smallrye/smallrye-jwt#222]
There are multiple ways to inject values from a `JWT`. From the latest MP JWT Spec, the following injection combinations must be supported (using `Long` as an example):

```java
@Inject
@Claim("long")
private long longClaim;
@Inject
@Claim("long")
private Long longClaimWrapper;
@Inject
@Claim("long")
private ClaimValue<Long> longClaimValue;
@Inject
@Claim("long")
private Optional<Long> longOptional;
@Inject
@Claim("long")
private ClaimValue<Optional<Long>> longClaimValueOptional;
@Inject
@Claim("long")
private JsonNumber longJson;
@Inject
@Claim("long")
private Optional<JsonNumber> longOptionalJson;
@Inject
@Claim("long")
private ClaimValue<JsonNumber> longClaimValueJson;
@Inject
@Claim("long")
private ClaimValue<Optional<JsonNumber>> longClaimValueOptionalJson;
```

There is also valid for other types like `Boolean`, `String` and corresponding `JsonValue` types. In #218, we realized that SmallRye JWT is not covering all cases and should be more consistent in how injection is done for the multiple combinations. The current implementation is able to handle the following injection combinations:

| Injection Type | Result |
| -------------  | -----|
|`long` | OK |
|`Long`| OK |
|`ClaimValue<Long>`| Fails |
|`Optional<Long>`| Fails |
|`ClaimValue<Optional<Long>>`| Fails | 
|`JsonNumber`| OK |
|`Optional<JsonNumber>`| OK |
|`ClaimValue<JsonNumber>`| OK |
|`ClaimValue<Optional<JsonNumber>>`| OK |

The main reason for injection to fail is a `ClassCastException` because values in the `claimSet` are usually stored as a `JsonValue` (except if it is a known claim and the type is set in the `Claims` enum).

So we need to determine the right type at injection point and then provide a conversion if required so the types match and injection work.

**Comment by sberyozkin** [comment]
@radcortez What is the problem with having the claims converted to JsonValue/Array/Object and then provide the conversion when needed ? This conversion from `JsonValue`/etc would have to be done for the custom claims like `Address` anyway, as opposed to the users guessing how it is represented internally before writing their address converter

**Comment by radcortez** [comment]
No problem at all. Right now the missing piece is conversion from the type stored in the claimSet (usually JsonValue) to another supported type when injection uses a ClaimValue wrapper.

For instance, you can see conversions being done here:
https://github.com/smallrye/smallrye-jwt/blob/b8adfd2e5e91d95419e4c9f0c6b10ee71ea27d3a/implementation/src/main/java/io/smallrye/jwt/auth/cdi/RawClaimTypeProducer.java

And that is why injection of `Long` or `long` work.

But there is no equivalent conversion code here:
https://github.com/smallrye/smallrye-jwt/blob/4f33aba47c7d177976ae5573e933ed2128426eea/implementation/src/main/java/io/smallrye/jwt/auth/cdi/ClaimValueWrapper.java

So when you try to inject a `ClaimValue<Long>` what you actually get is a `ClaimValue<JsonNumber>` and then the ClassCastException.

What we need is to determine the right type of `ClaimValue` and then apply the corresponding conversion.

**Comment by sberyozkin** [comment]
@radcortez can we keep the injection type [available in the constructor](https://github.com/smallrye/smallrye-jwt/blob/4f33aba47c7d177976ae5573e933ed2128426eea/implementation/src/main/java/io/smallrye/jwt/auth/cdi/ClaimValueWrapper.java#L37) and do the conversion from JsonValue/etc in `ClaimValueWrapper.getValue` ?

**Comment by radcortez** [comment]
Here is the code that I've written to fix the issue previously: 
https://github.com/radcortez/smallrye-jwt/blob/primitives-full-fix/implementation/src/main/java/io/smallrye/jwt/auth/cdi/ClaimValueWrapper.java

I believe I've done that. Just an additional method to unwrap the type in the constructor. And then `JsonUtils.convert` to pass the type to convert in `getValue`.

**Comment by sberyozkin** [comment]
@radcortez Cool, told you it would be easier for me to grok the changes if we go the smaller PR way :-).
So it all looks fine, I believe we can discuss/optimize the way the conversion of the claim set to JsonValue/etc in a separate issue. Your changes specific to this look fine, please follow up with a PR when you get a chance, thanks

**Comment by radcortez** [comment]
Done in #226.
