### ISSUE TITLE
Implement i18n logging and messages

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-jwt#227]
Follow the procedures defined in https://github.com/smallrye/smallrye-parent/wiki/I18N-Messages-and-Logging as part of implementing https://github.com/smallrye/smallrye-parent/issues/102 for all SmallRye projects

An example usage can be found in https://github.com/smallrye/smallrye-common

**Comment by ejba** [comment]
Hi, can I pick this one?

**Comment by radcortez** [comment]
Yes.

**Comment by radcortez** [comment]
BTW, nice to nice some other Portuguese people around :)

**Comment by ejba** [comment]
@mcserra's fault! 😄

**Comment by radcortez** [comment]
Thanks for contributing. Let me know if you need any help.

**Comment by ejba** [comment]
Do you have a list of project codes to be used? 

["projectCode should be 5 characters and start with SR to represent SmallRye"](https://github.com/smallrye/smallrye-parent/wiki/I18N-Messages-and-Logging#general-requirements)

**Comment by darranl** [comment]
For this project SRJWT sounds suitable.
