### ISSUE TITLE
Refetch mp.jwt.verify.publickey.location when receiving unfamiliar kid

### ISSUE THREAD

**Issue by sigmunau** [smallrye/smallrye-jwt#228]
The OpenID Connect core specification says in section 10.1.1 that users of the jwks_uri should re-retrieve the key set when it is asked to verify a signature with a unknown kid. https://openid.net/specs/openid-connect-core-1_0.html#RotateSigKeys smallrye-jwt does not do this, leading to `smallrye.jwt.jwks.refresh-interval` seconds (default 60) of failed requests each time the openid connect server smallrye-jwt is used with rotates it's keys. 

For me there also seems to be some issue with the refresh-interval, where it some times doesn't even start working after the refresh interval, and the service needs to be restarted after a key rotation

**Comment by sberyozkin** [comment]
> For me there also seems to be some issue with the refresh-interval, where it some times doesn't even start working after the refresh interval,

It may be due to the HTTP Cache-Control header
