### ISSUE TITLE
Update TCK to use Galleon provisioned server and use WildFly Elytron

### ISSUE THREAD

**Issue by darranl** [smallrye/smallrye-jwt#253]
By using Galleon it should be possible to provision a server with the minimal required dependencies.

The current unzip approach will also be making use of PicketBox which is deprecated ready to be removed in a future release, additionally we already know of PicketBox incompatibilities with later Java versions which will not be addressed.

**Comment by sberyozkin** [comment]
Hi @darranl Has this issue been resolved ? I've just merged #594

**Comment by sberyozkin** [comment]
Darran, you fixed it with #526, so this one can be closed
