### ISSUE TITLE
Dynamic secret key

### ISSUE THREAD

**Issue by rodrigohsb** [smallrye/smallrye-jwt#259]
Hey,

I'm trying to implement password reset flow, and in that flow, I need to have a unique secret key for each request to build a one-time link to prevent multiple requests with the same token.

Something like this:

```
val secret = 'MY_DYNAMIC_KEY'
val token = Jwt.claims() ..... .sign(secret)
```

Is there any way to achieve this?

**Comment by sberyozkin** [comment]
@rodrigohsb Hi, can you clarify please where you'd like the builder API to help ?  `sign` accepts `SecretKey`. Each token will have a unique `jti` identifier as well. What am I missing ? thanks

**Comment by rodrigohsb** [comment]
@sberyozkin Hi, sorry if wasn't clear enough.

I'm trying to `sign` with a `SecretKey` like this snippet using for quarkus:

```
val secretKey = SecretKeySpec(encodedPass.toByteArray(), SignatureAlgorithm.HS256.name)

val currentTimeInSecs = currentTimeInSecs().toLong()

return Jwt.claims().apply {
         issuer(issuer)
         subject(username)
         issuedAt(currentTimeInSecs)
         expiresAt(currentTimeInSecs + duration.toLong())
}
.jws()
.signatureKeyId(secret)
.sign(secretKey)
```
Apparently, this works fine:

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXM6aW8vdXNpbmctand0LXJiYWMiLCJzdWIiOiJyb2RyaWdvLmhhdXNAZ21haWwuY29tIiwiaWF0IjoxNTkyMjQzNTc5LCJleHAiOjE1OTIyNDcxNzksImp0aSI6IlVkWVlUTDQ5R25ZZlFBZjZqRHh2UEEifQ.z8JaMWKsB4t_eE4LjLZMojJSeT-fdShY83Tgz2_NAOQ`

 but i don't know how to parse it back. .. I'm trying this way and didn't work:
`parser.parse(token).subject`

Don't I need to parse with the same key? I searched the doc, but I couldn't figure out how neither here nor the quarkus.

If is not clear enough, feel free to argue 😄

**Comment by sberyozkin** [comment]
Hi @rodrigohsb Oh I see, thanks for the clarification. This is very important, have a simple parsing API built around `JWTParser`. Right now, one has to use Jose4J directly to verify the token  with the symmetric key:
```
private static Map<String, Object> getVerifiedClaims(String jwt, Key key) throws Exception {
        JsonWebSignature jws = new JsonWebSignature();
        jws.setCompactSerialization(jwt);
        jws.setKey(key);
        jws.verifySignature();
        return JwtClaims.parse(jws.getPayload()).getClaimsMap()); 
}
```

I'll add a utility code anyway, as I'm not sure yet how to change the interface, but for now, please use a function like this one...

**Comment by rodrigohsb** [comment]
@sberyozkin Thank you very much for your explanation.. I appreciate it! 😄 
It worked! 👏

**Comment by sberyozkin** [comment]
@rodrigohsb Thanks, I've opened #262
