### ISSUE TITLE
Add a method for generating a correct SecretKey

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#342]
A good number of projects (Jose4J itself, [JJWT](https://github.com/jwtk/jjwt#jws-key-create) and others) have the utility code for generating the keys. Jose4J itself will enforce that the key length meets the algorithm constraints so the users are not able to use the wrong key size, and Jose4J would report the required length, but having a correct key upfront would be useful.

This feature is not that important for the asymmetric algorithms, in the production one would expect the keys already distributed or available.

This is mainly of interest for generating the correct `SecretKey` - in scope of creating a JWT cookie, as again, one would expect the key be available on both ends.

[KeyUtils.generateSecretKey](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java#L244) already exists, but takes a String. So we need another one taking a signature or key encryption algorithm which will return the right key length. `Jose4j` may already have it so we will just wrap around it

**Comment by darranl** [comment]
I know this came up in the earlier discussions, I am actually in the middle of something similar in WildFly but for a completely different purpose - one thing I am questioning is if we should really prefer a KeyFactory over populating the SecretKeySpec manually in case a user is using some form of cerified cryptographic provider.
