### ISSUE TITLE
Property resolution within EARs

### ISSUE THREAD

**Issue by commodis** [smallrye/smallrye-jwt#360]
Greetings!

I was wondering how the property resolution within EARs is supposed to work.

Example:

<pre>
ear
  L  ejbjar
      L microprofile-config.properties
  L  war1
      L microprofile-config.properties
      L public.pem
  L  war2
</pre>

I configured `war1` to use `smallrye-jwt` via `@LoginConfig` and it is working by defining the properties `
mp.jwt.verify.publickey.location` and `
mp.jwt.verify.issuer`.

If `war2` is accessed an exception is thrown for missing said properties.

```
ERROR \[io.undertow.request\] (default task-1) UT005023: Exception handling request to /war2/: java.lang.IllegalStateException: JWTAuthContextInfo has not been initialized. Please make sure that either 'mp.jwt.verify.publickey' or 'mp.jwt.verify.publickey.location' properties are set. at io.smallrye.jwt//io.smallrye.jwt.config.JWTAuthContextInfoProvider.lambda$throwException$0(JWTAuthContextInfoProvider.java:430)
```

How is this supposed to work, if `war2` is not a `smallrye-jwt` defined web application? 
What is the resolution of this usecase? 

Cheers

**Comment by darranl** [comment]
This sounds like an issue to raise in the WFLY Jira project to be considered further.

Presently however our SmallRye JWT integration has just focused on securing a single deployment so in the context of an ear only one war is supported, the ambiguity here is the second war is getting picked up for JWT as well even though it contains no configuration of it's own - we possibly should be leaving that one to fall back to the container default security instead of applying the same policy as applied to war1.

**Comment by sberyozkin** [comment]
Hi @commodis as Darran said this is a WildFly concern how to manage smallrye-jwt across multiple wars, smallrye-jwt itself is deployment agnostic. Can you please move this issue to WildFly security GitHub ?

**Comment by commodis** [comment]
Sure, could you point me to the right repository? I only found the Wildfly Security Group but I am not aware which repository it should be moved to

---

https://github.com/wildfly-security

**Comment by sberyozkin** [comment]
@commodis Np, we'll try to do it with Darran when he is online :-), thanks for opening all the issues, please don't hesitate to open them here if you are not sure if they specific to WildFly or not and we can discuss and decide, thanks

**Comment by darranl** [comment]
Hello @commodis this is the Jira project to use to report issues against WildFly - https://issues.redhat.com/browse/WFLY - I would suggest raising it as a feature request for now as the present integration is intended for single web applications.

**Comment by sberyozkin** [comment]
@commodis Hi, OK. let me close this issue now, please follow @darranl 's advice (sorry if you already did :-) )

**Comment by commodis** [comment]
Thanks for pointing me there @darranl
The link to the issue is https://issues.redhat.com/browse/WFLY-14288
