### ISSUE TITLE
Allow to disable token validation

### ISSUE THREAD

**Issue by knutwannheden** [smallrye/smallrye-jwt#362]
In the context of a Quarkus application I would like to use the `quarkus-smallrye-jwt` extension and thus `smallrye-jwt` to set the Quarkus `SecurityIdentity` based on a JWT token passed as a HTTP header. However, since the JWT token will already have been validated (in our case by Azure API Management) I would like to disable the validation performed by `smallrye-jwt`, while still have the Quarkus extension set the `SecurityIdentity`.

I couldn't find any config property which would allow me to completely disable the validation, which is why I report this issue.

**Comment by knutwannheden** [comment]
If it would be more appropriate to report this against Quarkus, I can open an issue there and close this one.

**Comment by sberyozkin** [comment]
@knutwannheden sure, see https://quarkus.io/guides/security-jwt#custom-factories, please register a simple bean and do there what is required

**Comment by sberyozkin** [comment]
This is also documented in the smallrye-jwt docs here, so I think we can close this issue

**Comment by knutwannheden** [comment]
Yes, thanks for the pointer. As it apparently appears to be a not too uncommon use case, I wonder if it wouldn't make sense with a config property. But I will report that as a feature request against Quarkus then.

**Comment by sberyozkin** [comment]
@knutwannheden we've discussed a lot before, see, smallryw-jwt is all about the verification, so adding a first class property just to skip it is not really great IMHO; asking the users to add a super light-weight factory is not much :-), but the important point here is that that user takes the responsibility beyond just setting a property - which can become brittle - dev vs production mode property leak, etc

**Comment by knutwannheden** [comment]
Thanks for the explanation. At the Quarkus level it is of course also about parsing and setting the `SecurityIdentity`, but I get your point.

**Comment by knutwannheden** [comment]
Sorry for reopening this issue, but I looked at the workaround documented in the Quarkus guide, which you referenced, and have some concerns with it, which I don't have a satisfactory solution for.

If the token gets parsed directly using jose.4.j, the returned principal is missing some claims, which SmallRye JWT would otherwise set. Specifically I am referring to the `raw_token`, `sub`, and `groups` claims as set by `DefaultJWTTokenParser#parseClaims()`: https://github.com/smallrye/smallrye-jwt/blob/f3407388856e255d4703b0a3a2f4f56f4dfda286/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java#L157-L180

For this reason I consider the described workaround an insufficient solution in the context of a Quarkus application.

Possibly the `ProtectionLevel` enum could be extended with some constant like `NONE` to allow custom code to reuse the `DefaultJWTTokenParser` class.

In case this question is better discussed in a Quarkus issue, I can open a new issue there.

**Comment by sberyozkin** [comment]
@knutwannheden I'll push the code which follows the token verification to the abstract parser - you'd then inject the relevant configuration properties in your factory and set JWTAuthContextInfo and pass it to these parser

**Comment by knutwannheden** [comment]
@sberyozkin Sounds great, thanks!

**Comment by sberyozkin** [comment]
@knutwannheden I've just moved this code which updates the claims into public `PrincipalUtils`
