### ISSUE TITLE
JWTCallerPrincipal @RequestScoped

### ISSUE THREAD

**Issue by wicksim** [smallrye/smallrye-jwt#38]
I'm using Microprofile JWT for Thorntail (which is using this library) and in my `@ApplicationScoped` bean, the principal (JsonWebToken) isn't `@RequestScoped`.

According to the [specification 1.1](https://github.com/eclipse/microprofile-jwt-auth/releases/download/1.1/microprofile-jwt-auth-spec-1.1.pdf) (or even 1.0), "7.1.1. Injection of JsonWebToken", `JsonWebToken` needs to be `@RequestScoped`, so the current caller is injected in `@ApplicationScoped` beans. 

I'm not sure if `JWTCallerPrincipal` should get a `@RequestScoped`-annotation or if the thorntail-library should add a producer or something like this. But current behaviour is dangerous, because a second caller is getting identity from the first one.

So, is this the right place for this issue?

**Comment by kenfinnigan** [comment]
Can you comment on this @sberyozkin or @starksm64?

**Comment by starksm64** [comment]
Yes, this is something we ran into with Quarkus and I had asked @sberyozkin to port over the change to move away from the thread local behavior to properly support request scoping into our smallrye implementation.

**Comment by sberyozkin** [comment]
@wicksim, which Thorntail version are you using ? 
We have had [THORN-2110](https://issues.jboss.org/browse/THORN-2110) resolved for 2.1.0.Final, see [this PR](https://github.com/thorntail/thorntail/pull/1071/files).

**Comment by wicksim** [comment]
I'm using 2.3.0.Final. So, there must still be an issue here. Couldn't it be that principal itself is still `@ApplicationScoped` and therefore only injected once?

**Comment by sberyozkin** [comment]
@wicksim, thanks, please watch [THORN-2390](https://issues.jboss.org/browse/THORN-2390). Going to start looking into it next Tue with few days off on the way. Let me close this issue as it is really a Thorntail specific one.

**Comment by sberyozkin** [comment]
@wicksim FYI, the issue has been resolved in Thorntail 2.5.0-SNAPSHOT
