### ISSUE TITLE
Fix configuration key location inconsistency

### ISSUE THREAD

**Issue by huw0** [smallrye/smallrye-jwt#395]
```
smallrye.jwt.encrypt.key-location
smallrye.jwt.sign.key-location
smallrye.jwt.verify.key.location
mp.jwt.verify.publickey.location
```

Configuration keys with dashes should be replaced with dots, making them all consistent and ensuring that smallrye is consistent with microprofile convention.

Probably I'm not the first person who has copied and modified the verify configuration and then spent some time debugging why the sign config appears to be unset.

Probably desirable to support old config keys for awhile to prevent breaking backwards compatibility.

**Comment by sberyozkin** [comment]
I agree, I think I recorded this task somewhere, may be in the current MP JWT PR (which will need to be refreshed in due time).
We can do it for 3.0.0 Final I guess

**Comment by sberyozkin** [comment]
I'll deprecate it in 2.4.x so that we can drop the old properties in 3.0.0 final
