### ISSUE TITLE
Allow signing key to be loaded directly from config

### ISSUE THREAD

**Issue by huw0** [smallrye/smallrye-jwt#396]
Currently it is possible for the verify key to be passed in as a string using `mp.jwt.verify.publickey`.

However the same is not possible for encrypt and sign keys which only support `smallrye.jwt.encrypt.key-location` and `smallrye.jwt.sign.key-location`.

This makes sense for config that is bundled with an application since clearly this would not be good practice. It also works well in k8s (and similar) environments where secrets can be passed in as files.

However when writing custom configuration sources it becomes necessary to write the key to disk before it can be used. Therefore I think it would be good if keys could be passed in directly to support this use case.

`smallrye.jwt.encrypt.key`
`smallrye.jwt.sign.key`

**Comment by sberyozkin** [comment]
@huw0 It is intentional - I did not want to let the users to keep the private keys inlined in the configuration - one can't even replace it with some location. So I'll close it shortly, thanks
