### ISSUE TITLE
Behave identically for http jwks url

### ISSUE THREAD

**Issue by lebetz** [smallrye/smallrye-jwt#397]
At the moment the code behaves different depending if jwks url is configured as http or as https.

In our case we are running the jwks provider in the same Kubernetes tenant as the backend. The provider is not able to provide the keyset over an https url. And because the traffic keeps inside the tenant it is also not needed for us from a security perspective.
But if I configure the keyset location with http url in smallrye-jwt, the refresh mechanism is not initialized and so JWT verification fails after the next key rotation.

Is there a specific reason for the different behavior? It would be great if https jwks would work identically to https?

**Comment by sberyozkin** [comment]
@lebetz Not really, for now it is based on Json4J `HttpsJwks`. I guess we can do a forced refresh for a JWK set fetched from the `HTTP` url too
