### ISSUE TITLE
Support OIDC client web servers better 

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#41]
This may become an MP-JWT issue, but some initial experiments can be done in smallrye-jwt.
Currently, as far as MP-JWT is concerned it can work well in cases where OIDC client (browser or webserver) acquires an access token and uses them to access RSs which is where MP-JWT helps.

For example, OIDC authorization code flow would typically involve a web server acting as OIDC client, redirecting the user to IDP, getting the authorization code, exchanging it for the access and ID tokens, and using the access token to make the remote RS calls.

Now, if MP-JWT is used in such the OIDC client then it can easily validate either ID or the access token, but it can't redirect the user back to IDP and it can't keep some session state. In fact it may better be done at the Quarkus/Thorntail/etc level, but I'm opening the issue here for some further investigations

**Comment by sberyozkin** [comment]
Having said it, it could be simpler/better align MP-JWT in such cases with the specific IDP adapter implementations such as Keycloak which are optimized around supporting various flows better.
Will keep this issue for now though, in case adding some simple portable mechanism (or callbacks to link with KC, etc) will make sense

**Comment by aaronanderson** [comment]
The new [Quarkus OIDC extension](https://quarkus.io/guides/security-openid-connect-web-authentication) is available and works fine for me. I think OIDC authentication flows are outside the purview of the MP-JWT specification.

**Comment by sberyozkin** [comment]
I'm going to close this one for now
