### ISSUE TITLE
Support Accessing JWT in Aspect Classes

### ISSUE THREAD

**Issue by dentonmwood** [smallrye/smallrye-jwt#435]
From the MP-JWT spec:

> An MP-JWT implementation must support the injection of the currently authenticated caller as a JsonWebToken with @RequestScoped scoping which must work even if the outer bean is @ApplicationScoped

I was hoping this meant all request-scoped beans, and not just REST endpoint classes underneath an Application class. We use AOP to provide security, and when I try to inject the JsonWebToken class into a request-scoped aspect class to process the user, I get Weld exceptions about unsatisfied dependencies. Injection into request-scoped REST classes deploys without Weld errors.

Further details for reproduceability:
* Server: WildFly 22.0.0
* POM import:

```
<dependency>
    <groupId>org.eclipse.microprofile.jwt</groupId>
    <artifactId>microprofile-jwt-auth-api</artifactId>
    <scope>provided</scope>
</dependency>
```

* web.xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd" version="3.1">
<security-constraint>
  <web-resource-collection>
	  <web-resource-name>LoggedIn resources</web-resource-name>
	  <url-pattern>/rest/person/*</url-pattern>
	  <url-pattern>/rest/user/*</url-pattern>
  </web-resource-collection>
</security-constraint>

    <context-param>
        <param-name>resteasy.role.based.security</param-name>
        <param-value>true</param-value>
    </context-param>
</web-app>
```

**Comment by sberyozkin** [comment]
@dentonmwood Hi, TCK test exists which asserts an `ApplicationScoped` endpoints can get `JsonWebToken` injected.
@darranl @SoniaZaldana  - should this issue be moved to WildFly ?

**Comment by sberyozkin** [comment]
@dentonmwood Please open a new issue in  https://issues.redhat.com/browse/WFLY , 
as there is nothing we can do about this issue at the smallrye-jwt level - such issues may be handled at the integrating container level.
CC @darranl @SoniaZaldana

Darran, Sonia, if you think this is a smallrye-jwt specific issue then please reopen it :-)
