### ISSUE TITLE
Distinguish between unresolvable and invalid keys

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#437]
If we have a JWK key set, for example, coming from Keycloak and a token has a `kid` which does not match any JWK in this JWK key set then an `UnresolvableKeyException` will be thrown and - `500` reported in `jwt-http-mechanism`.
But this is a case of `401` - keys are available and valid - but the token is effectively invalid.
Some thinking is required how to do it cleanly

CC @darranl @SoniaZaldana

**Comment by Skyllarr** [comment]
I am working on this one.
