### ISSUE TITLE
SmallRye-JWT with JSF

### ISSUE THREAD

**Issue by dentonmwood** [smallrye/smallrye-jwt#440]
Is integrating SmallRye-JWT with JSF supported? We have a JSF 2.3 client running on WildFly which we'd like to use MP-JWT with, but I can't seem to get the integration working. In lieu of @LoginConfig, I specified the login config in the web.xml file:

```
<security-constraint>
    <web-resource-collection>
        <web-resource-name>User</web-resource-name>
        <url-pattern>/*</url-pattern>
    </web-resource-collection>
    <auth-constraint>
        <role-name>user</role-name>
    </auth-constraint>
    <user-data-constraint>
        <transport-guarantee>NONE</transport-guarantee>
    </user-data-constraint>
</security-constraint>

<login-config>
    <auth-method>MP-JWT</auth-method>
</login-config>

<security-role>
    <role-name>user</role-name>
</security-role>
```

However, when I load the page with a bearer token, it returns a 403, and it won't hit our servlet filter.

**Comment by sberyozkin** [comment]
@dentonmwood thanks, this issue belongs in the WildFly GitHub - please move it there, thanks CC @darranl

**Comment by dentonmwood** [comment]
@sberyozkin thanks for the clarification!

**Comment by sberyozkin** [comment]
@dentonmwood  np, thanks - `smallrye-jwt` is a self-contained library while the integrations are done ate the higher level in WildFly, and other propjects

**Comment by darranl** [comment]
FYI as a discussion topic here would be the place to begin https://groups.google.com/g/wildfly
