### ISSUE TITLE
Support for Proxy Host/Port/Auth in Key Location

### ISSUE THREAD

**Issue by benjaques** [smallrye/smallrye-jwt#460]
Hi all,

Currently leveraging the smallrye-jwt extension in Quarkus. We have an issue in that some of our hosting environments are behind various corporate proxies and require a proxy auth before the request to the external JWT location can be made. Of course, we can simply set the JVM arguments (-Dhttp.proxyHost,Port,etc) inside our image, but we'd like to restrict the proxy access to this specific refresh command for security reasons.

It looks like the jose4j lib has direct support for setting proxy on connections [here](https://bitbucket.org/b_c/jose4j/src/f6655ef41cff1737b52c8ba9285e819843a94b37/src/main/java/org/jose4j/http/Get.java#lines-339).

So I think it would just involve adding a few proxy config properties (hostname/username/password/port/enabled ?), creating a proxy object and passing that to the httpsjwk connection so that refreshes go through the proxy first. I'd be willing to take a crack at it if you agree there's a need.

Let me know what you think -- thanks!

**Comment by sberyozkin** [comment]
Hi @benjaques 

It feels like it is a bit out of scope for smallrye-jwt - but at the same time, key resolvers do use `HttpsJwk`, so making sure JWKS acquisition/refreshment works with HTTP Proxies at the smallrye-jwt level likely makes sense.
Perhaps we should introduce `Proxy` configuration object (`smallrye.jwt.http.proxy.username` etc) and pass it around with `JWTContextInfo` for the resolvers to use it to init `HttpsGet`.

Please investigate
thanks

CC @darranl @MikeEdgar @radcortez
