### ISSUE TITLE
Let users disable the issued at claim requirement

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#469]
A Quarkus user has reported that with smallrye-jwt `3.x` the tokens without `iat` are rejected.

MP JWT 1.2 enforces an MP JWT 1.1.1 requirement that `iat` is one of the required claims (not all of the claims from that MP JWT 1.1.1 list are enforced) but `iat` is one of the very essential claims so it is enforced.

The problem is the user is working with a 3rd party issuer which can not be changed in a short term.

So we need to add a smallrye-jwt specific property to let the users make it optional

CC @@xwoker

**Comment by sberyozkin** [comment]
@MikeEdgar Hi Mike, recall you added a time to live property - this one, if set, requires an `iat` - so I'd like to address this issue in terms of that property - I'm a bit hesitant to add a dedicated property to let users ignore `iat` since it is really an important property.
So what I'd like to do is to check if the time to live property is set and if it is <=0 then no time to live constraint has to be enforced and hence the `iat` requirement can be relaxed - so by default it is required, but if the users don;t want they set the time to live property to 0 - as this is what it means if `iat` is not enforced the token may have been around for a year...

Do you agree ?

**Comment by xwoker** [comment]
Since the `smallrye.jwt.time-to-live` property seems to have no default set, my assumption would be that there value has to be set to` > 0` in order to trigger the `iat` check. But - at least it seems to me - the `iat` is checked even if the property isn’t set at all.

**Comment by MikeEdgar** [comment]
> check if the time to live property is set and if it is <=0 then no time to live constraint has to be enforced

:+1: @sberyozkin, that sounds like a reasonable approach to me.

**Comment by sberyozkin** [comment]
@xwoker Right, so I'll fix this issue as described above
