### ISSUE TITLE
KeyLocationResolver does not match on key ID

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-jwt#51]
The `io.smallrye.jwt.auth.principal.KeyLocationResolver.tryAsJWKx(String)` does not compare the `kid` argument to the `kid` entry on the JWK(S) object(s) fetched from `mp.jwt.verify.publickey.location`.

**Comment by sberyozkin** [comment]
@MikeEdgar a PR will be coming shortly

**Comment by sberyozkin** [comment]
@MikeEdgar FYI, #61
