### ISSUE TITLE
CDI extension and JSR-375

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-jwt#52]
Is there any potential for this library to incorporate a CDI extension and perhaps an implementation of `HttpAuthenticationMechanism`, falling back to the JAX-RS filter if no runtime is available? Using JSR-375 seems like a natural fit for an implementation of MP-JWT (knowing that the API does not use JSR-375).

**Comment by kenfinnigan** [comment]
@sberyozkin @starksm64 Any thoughts?

**Comment by starksm64** [comment]
We had tried to think about including JSR-375 support on MP-JWT but its dependency on servlet spec classes was something we could not include in the current MP release due to restrictions on the core dependencies. We can certainly explore including it in smallrye though.

**Comment by MikeEdgar** [comment]
Sounds good. I can put together a PR to show what I'm thinking to help determine if it aligns with the direction you want to take smallrye JWT.

**Comment by sberyozkin** [comment]
By the way, I'd like to investigate the option of replacing the factory mechanism with the CDI Producer mechanism to make the way the custom validators are loaded consistent between Quarkus/Thorntail/etc

**Comment by MikeEdgar** [comment]
I pushed some of the ideas I've been testing for this: https://github.com/MikeEdgar/smallrye-jwt/tree/52_cdi_extension. It also includes the changes from my #55 PR.
Let me know if you have any feedback on the changes in that branch or if it would be easier to put them in a separate PR.

**Comment by MikeEdgar** [comment]
@sberyozkin - I added my replies. I did have one question regarding the method-level security annotations.

**Comment by MikeEdgar** [comment]
@sberyozkin, I added an additional commit including the AuthZ filters from Thorntail. Those classes could be removed if we go ahead with these changes here.

Note that I thought the default behavior for those filters should be to throw `ClientErrorException`s so that applications could handle the situation and respond with their own formats, if desired. 

I also had the `DenyAllFilter` directly throw a `ForbiddenException`. I think the semantics of `@DenyAll` may be more in alignment with 403 - i.e. authentication will not change the results of future requests. 

Thoughts?

https://github.com/MikeEdgar/smallrye-jwt/commit/a6c952a1e4790678ad62de6ef3b0a7109acd63fd

**Comment by sberyozkin** [comment]
Hi @MikeEdgar, sorry missed your comment.  Sure making it possible to add some application specific logging, etc at the exception mapper level makes sense IMHO, @michalszynkiewicz, FYI.

What I'm not sure about yet if whether the smallrye-jwt should ship its own CDI extension or is it something that should be left up to the integrating runtimes. Especially given that the one you propose will attempt to auto load the JSR-375 mechanism. I'll need to experiment with both Thorntail (which has its own extension) and Quatrkus (which uses another mechanism), perhaps we can split your contribution into 2 PRs, with the authentication mechanism support coming in the PR2, let me experiment this week.
By the way, can you please reply to the question for  #55, thanks

**Comment by MikeEdgar** [comment]
@sberyozkin - I'm tending to agree with your comments regarding the code for activating smallrye-jwt. I am currently trying to get MP JWT working with an application running in traditional Wildfly and this thread is making me realize that the things I'm proposing may be better placed in a wrapper/shim library intended for use by application developers.

**Comment by sberyozkin** [comment]
Having the mechanism shipped with smallrye-jwt is a nice idea, can probably help to remove Undertow specific code eventually from Thorntail/Quarkus, I'm just not sure yet of the possible side-effects if it will be created inside the smallrye-jwt extension...

**Comment by sberyozkin** [comment]
@MikeEdgar Can you please open a PR ? Your changes look good. As discussed, may be lets split them into two PRs ? The 1st PR would include everything but `SmallRyeJWTAuthCDIExtension` (and I guess the beans.xml and the service loader resource). As I mentioned Quarkus uses its own mechanism, Thorntail - its own extension, may be it all can be consolidated but I'd rather try to do it in the 2nd step.  

I'll then look at removing the JAX-RS filters from Throntail. And will also try to see if the authenication mechanism you have created can be used, etc.

Does it sound good to you ?

**Comment by MikeEdgar** [comment]
@sberyozkin - sounds good. I should be able to get this over shortly.

**Comment by MikeEdgar** [comment]
@sberyozkin - what do you think about keeping the code for the `SmallRyeJWTAuthCDIExtension` but with comments that it is not enabled, and remove the `beans.xml` and the service loader file?

**Comment by sberyozkin** [comment]
@MikeEdgar +1, lets keep it and perhaps we can generalize it further later on such that it can be used OOB for all the integrations, but indeed lets ship it for now with beans.xml and the loader resource :-) thanks

**Comment by sberyozkin** [comment]
@MikeEdgar Thank you
