### ISSUE TITLE
DefaultJWTParser cached PublicKey location

### ISSUE THREAD

**Issue by dnfesenk** [smallrye/smallrye-jwt#521]
I try to parse JWT token from string like [this](https://quarkus.io/guides/security-jwt#create-jsonwebtoken-with-jwtparser), but if I use JWT auth on method that parsed token from string, I can't override public key location, because DefaultJWTParser ignore it. So, if I inject JWTParser, it created singleton of JWTCallerPrincipalFactory, that has final field of DefaultJWTTokenParser (on DefaultJWTCallerPrincipalFactory instance). If I try this:
`jwtParser.parse(token, JWTAuthContextInfo("newPublicKey.pem", "newIssuer"))`
newPublicKey.pem will de ignored

**Comment by sberyozkin** [comment]
@dnfesenk There are more methods available, please use

https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTParser.java#L64

**Comment by dnfesenk** [comment]
@sberyozkin Thanks! But how can I create PublicKey from jwk location url?

**Comment by sberyozkin** [comment]
@dnfesenk Why would you like to override the location ?

**Comment by dnfesenk** [comment]
@sberyozkin because I have a special case to validate and parse jwt-token from another auth-server. I found the way, thank you!

**Comment by sberyozkin** [comment]
@dnfesenk sounds good; pointing to a JWK set with more than one key would be one approach, as long as the token contains `kid` it would work

**Comment by sberyozkin** [comment]
@dnfesenk I think I'll resolve this issue by updating the docs, advising to avoid injecting `JWTParser` and instead use `new DefaultJWTParser()` if the key requirements are changing dynamically or, when possible, use `JsonWebKeySet`
