### ISSUE TITLE
JwtConsumer#processContext(JwtContext) called twice

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-jwt#53]
The jose4j method `org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtContext)` is called twice from `DefaultJWTTokenParser`. First (indirectly) during the call to `org.jose4j.jwt.consumer.JwtConsumer.process(String)` and then directly from `DefaultJWTTokenParser` after returning from `process`.

**Comment by sberyozkin** [comment]
Thanks for spotting [it](https://bitbucket.org/b_c/jose4j/src/a42256ceb7bb6af590958bf79987f06112bd212f/src/main/java/org/jose4j/jwt/consumer/JwtConsumer.java#lines-433). @starksm64 FYI

**Comment by sberyozkin** [comment]
See #60
