### ISSUE TITLE
In DefaultJWTTokenParser first keyResover wins no matter what authInfoContext specifies

### ISSUE THREAD

**Issue by spike83** [smallrye/smallrye-jwt#538]
I try to call an oidc secured service out of an oidc secured service. So the default `publicKeyLocation` is set to my IDP in order to verify tokens. When trying to validate the JWT from external service I cannot specify another `publicKeyLocation` in a dedicated `JWTAuthContextInfo`.

In https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java#L239 the `VerificationKeyResolver` should be returned. 

Now when using more than one IDP I create a jwtParser and pass an authContext to its parse method specifying another AuthInfo object with another publicKeyLocation but the method does not check if the existing `VerificationKeyResolver` matches the `authContextInfo` so I get the wrong keyResolver returned and `SRJWT07005: Failed to load a key from ...` error.

Is this a bug or am I doing something wrong?

**Comment by sberyozkin** [comment]
@spike83 `smallrye-jwt` is not designed to be multi-tenant such that a single parser can be used to verify the tokens signed by different providers.
If you need to support more than one key at a time, where tokens are coming from the same provider then using `Json Web Key Set` is the simplest option.
But if each token may have a different issuer then one should create several `DefaultJWTParsers` to cover all the providers:

```
JWTParser parser = new DefaultJWTParser(new JWTAuthContextInfo("key1.pem"), new DefaultJWTCallerPrincipalFactory());
JWTParser parser2 = new DefaultJWTParser(new JWTAuthContextInfo("key2.pem"), new DefaultJWTCallerPrincipalFactory());
```

A single parser can't keep switching the verificators or keep building them dynamically per every request, this is a key verifier is cached.

I'll resolve this issue later once I update the docs, I already did it earlier but the update was not complete

**Comment by spike83** [comment]
@sberyozkin thanks for the quick reply. I have worked out similar thing yesterday but in context of CDI (quarkus). In my case the `JWTAuthContextInfo` is injected so I can inject a mock during tests.

I think especially a remark in here https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTParser.java#L43-L53 would have pointed me into the right direction. Before I've just taken an injected instance of this and tried to run parse with different `JWTAuthContextInfo` which from the javadoc seems to be possible.

**Comment by sberyozkin** [comment]
@spike83 I'll update the code a bit later on to ensure a new factory instance is created for all but a single arg `parse` method accepting a token only - it will avoid the problem with the cached key resolver.  `new DefaultJWTParser(new JWTAuthContextInfo("key1.pem"), new DefaultJWTCallerPrincipalFactory())` works but the users should not be required ti do it, `new DefaultJWTParser(new JWTAuthContextInfo("key1.pem")), new DefaultJWTParser(new JWTAuthContextInfo("key2.pem"))` or `parser.parse(myKey)` should just work
