### ISSUE TITLE
Setting the expiry grace period to 0 fails to verify the expired tokens 

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#546]
A user has reported that when changing a grace period from the default 60 secs to 0 the expired tokens can be accepted - it will need to be reproduced with a test and fixed

**Comment by maxant** [comment]
see https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Issue.20with.20JWT.20expiry.20grace.20period.3F/near/267730986

I'll try writing a test in the next few days
