### ISSUE TITLE
Allow Subject Claim Override

### ISSUE THREAD

**Issue by Diom** [smallrye/smallrye-jwt#558]
I have been trying to ignore the subject as provided by an IDP and use a different claim as the subject. However it appears that this is not currently possible with SmallRye JWT

        if (!claimsSet.hasClaim(Claims.sub.name())) {
            String sub = findSubject(authContextInfo, claimsSet);
            claimsSet.setClaim(Claims.sub.name(), sub);
        }

See [here](https://github.com/smallrye/smallrye-jwt/blob/752fb559d2342724bcb04117eca37dbc043a8600/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalUtils.java#L45). Essentially the config property `smallrye.jwt.path.sub` seems to only apply when no existing `sub` claim is on the JWT. This does match the accompanying docs, which says:

>This property can be used if a token has no 'sub' claim but has the subject set in a different claim
 
I think it is counter-intuitive that it acts as a fall-back rather than an override. Obviously my opinion is just that so I would propose adding a new boolean config property:

`smallrye.jwt.path.sub.override`

Enabling the flag would cause the `findSubject` to always be executed. Something along the lines of:

        if (subjectPathOverride || !claimsSet.hasClaim(Claims.sub.name())) {
            String sub = findSubject(authContextInfo, claimsSet);
            claimsSet.setClaim(Claims.sub.name(), sub);
        }

**Comment by sberyozkin** [comment]
@Diom IMHO we should not be doing it. Th existing code does not create a new content in a token it only duplicates it into a given standard claim if the actual content is located in a custom complex or simple claim.
Overriding the existing token content as part of the token verification is out or scope for smallrye-jwt.

I believe that such a requirement should be addressed at a different level. For example, if you work with Quarkus, you can use `SecurityIdentityAugmentor` to create a custom `JsonWebToken` principal which will delegate to the already provided one but only override `getClaim(Claims.sub)`. Similarly, you can customize it at the custom JAX-RS `ContainerRequestFilter`

**Comment by sberyozkin** [comment]
What is the use case ?

**Comment by Diom** [comment]
@sberyozkin You might be right that it should be addressed at a higher level actually, rather than SmallRye.
Use case is essentially that the IDP has a second 'username' claim that also is guaranteed to be unique in our scenario (integration of another external IDP, which populates the 'username' claim). In our case one of the microservices is responsible for fetching data from another external system based on the sub from the original IDP. Having this would mean we could use the Principle directly without a secondary lookup on the claims... and we could change it back to the standard 'sub' claim if the integration of the IDPs ever gets tidied up.

I was hoping to avoid all code changes! 😁

**Comment by sberyozkin** [comment]
@Diom thanks, perhaps this specific endpoint should check the specific non `sub` claim ?
