### ISSUE TITLE
`mp.jwt.verify.publickey.location` needs to support TLS configuration

### ISSUE THREAD

**Issue by kdubb** [smallrye/smallrye-jwt#571]
This URL's need to be able to configure TLS parameters (e.g. CA, Cert, Key).

We use an internal service (via a Vault plugin) that generates internal JWTs for micro-service authorization and provides public keys for verification via a standard JWKs endpoint. With TLS required for Vault we cannot load our verifications keys from this endpoint since we use a cluster local self-signed CA.

**Comment by kdubb** [comment]
For use we need a minimum of configuration the trusted CA(s). This is supported by the Jose4j used in the implementation but there is no configuration in Smallrye JWT to make it work.

**Comment by sberyozkin** [comment]
Hi @kdubb It makes sense, it is similar to #460. Would you like to give it a try ? I guess a dedicated configuration group will be needed

**Comment by MikeEdgar** [comment]
@sberyozkin, @kdubb - I will also have a need for this feature soon. Let me know if you won't have an opportunity and I may be able to look at it. The only question is - what should the content of the new configuration property be? The simplest would probably be the trusted CA's PEM certificate.

**Comment by kdubb** [comment]
`HttpsJwks` (via `Get`) easily supports `setTrustedCertificates` and `setHostnameVerifier` and for extended configuration it does have a `setSslSocketFactory`.

As I stated all we require is trusted CA's so I'm probably gonna wire that up along with hostname verification and leave the rest up to a different PR.

**Comment by sberyozkin** [comment]
@kdubb @MikeEdgar I'm looking at it right now and will open a PR shortly
