### ISSUE TITLE
Option to change Authorization header to another one

### ISSUE THREAD

**Issue by SMakhrov** [smallrye/smallrye-jwt#580]
Hello!

Does exist any way to change Authorization header to another one? For example - to use X-JWT-Assertion?
Default logic:
**Authorization** header with value **Bearer** [token]
Target logic:
**X-JWT-Assertion** header with value [token]

**Comment by sberyozkin** [comment]
It is an `mp.jwt.token.header` property, see https://smallrye.io/docs/smallrye-jwt/configuration.html
