### ISSUE TITLE
smallrye.jwt.client.tls.hosts or smallrye.jwt.client.tls.trusted.hosts

### ISSUE THREAD

**Issue by agreedSkiing** [smallrye/smallrye-jwt#626]
# Issue
In the [configuration.adoc](https://github.com/smallrye/smallrye-jwt/tree/main/doc/modules/ROOT/pages/configuration.adoc) file the configuration parameter for trusted hosts is `smallrye.jwt.client.tls.trusted.hosts` but whilst searching for it in the code base it is instead called `smallrye.jwt.client.tls.hosts` in [JWTAuthContextInfoProvider.java](https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L515).
This small difference might leed to some problems in the future.

# Solutions
1. Change configuration.adoc to match code
2. Change code to match configurations.adoc configuration parameter name (this would make name match the existing javadoc)
3. Do nothing

**Comment by sberyozkin** [comment]
@agreedSkiing Thanks for spotting it, it is a typo in the docs, option 1 is a solution.
