### ISSUE TITLE
Integration with Jakarta IdentityStore

### ISSUE THREAD

**Issue by amoscatelli** [smallrye/smallrye-jwt#656]
I don't understand what's the current state of integration with IdentityStore.

Cooperation with IdentityStore is somehow described in the spec :
https://download.eclipse.org/microprofile/microprofile-jwt-auth-2.0/microprofile-jwt-auth-spec-2.0.html

I need to provide more groups/roles using an additional IdentityStore (with ValidationType PROVIDE_GROUPS) because my roles are not included in the JWT.

Am I trying to do something wrong ?

**Comment by darranl** [comment]
Where are you using Smallrye JWT?

**Comment by amoscatelli** [comment]
I am using Wildfly 27.0.0 Final.
I have set in my web.xml :

    <login-config> 
        <auth-method>MP-JWT</auth-method>
    </login-config>

mp.jwt.verify.publickey.location is set as a java system property.

io.smallrye.jwt.auth.mechanism.JWTHttpAuthenticationMechanism is then called when I try to access my apis.
The JsonWebToken principal is parsed correctly, I can see my preferred_username.
jwtPrincipal.getGroups() returns an empty list, and that's correct.

What seems to be wrong is that my @ApplicationScoped IdentityStore is not called.
I expected getCallerGroups method to be called.

According to this definition : 

```
IdentityStore is a mechanism for validating a caller's credentials
and accessing a caller's identity attributes. It can be used by an
authentication mechanism, such as a Jakarta Security {@link HttpAuthenticationMechanism}
or a Jakarta Authentication {@link ServerAuthModule}.
```

I expected io.smallrye.jwt.auth.mechanism.JWTHttpAuthenticationMechanism to call additional IdentityStore s, but I found no reference to jakarta.security.enterprise.identitystore in the whole smallrye-jwt (jakarta branch).

Am I mistaken ?

**Comment by amoscatelli** [comment]
@darranl 

I would expect something like this : 
https://github.com/smallrye/smallrye-jwt/pull/657

**Comment by sberyozkin** [comment]
Not sure why resolving #657 did not close this issue, closing manually

**Comment by sberyozkin** [comment]
@amoscatelli Just reopening it until you create a PR against the main branch as well, I did not want to mess with cherry-picking/merging your PR from the jakarta branch into the main branch to avoid any confusion. I'll include your PR against main, after you make it, in 3.6.1, early next year, thanks
