### ISSUE TITLE
Add the ability for JWTTokenParser to not check signature on all tokens when mp.jwt.verify.publickey.location is set

### ISSUE THREAD

**Issue by AhmedEzzat12** [smallrye/smallrye-jwt#703]
A project may have multiple types of JWTs, I have some JWTs that are only encrypted "JWE", and when I try to decode them they fail, because `JWTAuthContextInfo` has value in `publicKeyLocation` so it assumes that the token is also signed.

**Comment by sberyozkin** [comment]
@AhmedEzzat12 In that case the only realistic alternative is to have a few `JWTParser` instances created, each initialized accordingly

**Comment by AhmedEzzat12** [comment]
Thanks for the help, this works. I was thinking in a different direction.
I'll close the issue now
