### ISSUE TITLE
Support multiples configurations

### ISSUE THREAD

**Issue by corentin59** [smallrye/smallrye-jwt#704]
It is possible today to configure the following entries:
mp.jwt.verify.publickey.location
mp.jwt.verify.issuer

However, these remain specific to the entire application, some more generic applications may need to read JWTs signed by different providers (which are selected based on a route or something else).

The implementation of a name can look like this:
mp.jwt.verify.publickey.NAME1.location
mp.jwt.verify.publickey.NAME1.issuer

mp.jwt.verify.publickey.NAME2.location
mp.jwt.verify.publickey.NAME2.issuer

etc...

**Comment by sberyozkin** [comment]
@corentin59 Multi-tenancy is not really supported at the smallrye-jwt level - the question - how to choose the right configuration for a given token, which would for example require checking HTTP headers and at the core smallrye-jwt level it is not possible - it can be done for example at the Quarkus or WildFly level. 
In smallrye-jwt, you can have it supported by creating multiple JWTParser instances, configured appropriately, and then call the right one from the related endpoint.
If you work with Quarkus, then you can try `quarkus-oidc` which does support multiple configurations - that would work fine if the verification keys are fetched from OIDC providers

**Comment by sberyozkin** [comment]
Let me close this one for the moment
