### ISSUE TITLE
Validate Jwt build with different keys and algorithms

### ISSUE THREAD

**Issue by SamyLegal** [smallrye/smallrye-jwt#721]
Hi,

I develop a Quarkus application which must validate jwt created by a NodeJs application.
This NodeJs application authorize to create Jwt from multiple keys, symmetric key and asymmetric keys.

For validate Jwt build with multiple keys, i have used a JsonWebKeySet and that works if i use the same algorithm for my all keys but if in my keyset, i use different algorithm that does not work.

Exemple of Json Web Key Set with use of differents algorithms

```json
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "kid": "asymmetric-keys-back",
      "n": "livFI8qB4D0y2jy0CfEqFyy46R0o7S8TKpsx5xbHKoU1VWg6QkQm-ntyIv1p4kE1sPEQO73-HY8-Bzs75XwRTYL1BmR1w8J5hmjVWjc6R2BTBGAYRPFRhor3kpM6ni2SPmNNhurEAHw7TaqszP5eUF_F9-KEBWkwVta-PZ37bwqSE4sCb1soZFrVz_UT_LF4tYpuVYt3YbqToZ3pZOZ9AX2o1GCG3xwOjkc4x0W7ezbQZdC9iftPxVHR8irOijJRRjcPDtA6vPKpzLl6CyYnsIYPd99ltwxTHjr3npfv_3Lw50bAkbT4HeLFxTx4flEoZLKO_g0bAoV2uqBhkA9xnQ"
    },
    {
      "kty": "oct",
      "kid": "symmetric-keys-front",
      "k": "djF4Y2ZGcDRBTEhzU0NJaVA3Vm01aDFOSERhakUxcjE="
    }
  ]
}
```

For me the problem came from of the key "mp.jwt.verify.publickey.algorithm" that it can take only one algorithm.

If i want to validate a key with an algorithm different of one defined in this key i have this error : 

```java
Caused by: org.jose4j.lang.InvalidAlgorithmException: 'RS256' is not a permitted algorithm.
        at org.jose4j.jwa.AlgorithmConstraints.checkConstraint(AlgorithmConstraints.java:80)
        at org.jose4j.jws.JsonWebSignature.getAlgorithm(JsonWebSignature.java:280)
        at org.jose4j.jws.JsonWebSignature.getAlgorithm(JsonWebSignature.java:261)
        at org.jose4j.jws.JsonWebSignature.verifySignature(JsonWebSignature.java:235)
        at org.jose4j.jws.JsonWebSignature.getPayloadBytes(JsonWebSignature.java:80)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
        ... 57 more
```

Have you got a solution for this problem ?
Is that possible to give multiple algorithm to the key "mp.jwt.verify.publickey.algorithm" ?

Thank you for the answer

**Comment by sberyozkin** [comment]
@SamyLegal Hi, right now, at the MP-JWT level, it can't be done in a declarative manner, no multi tenant setup assuming a single endpoint accepting tokens from multiple issuers using different algorithms is possible. Limited support only allowed for the decryption keys where either `RSA-OAEP`  or `RSA-OAEP-256` can both be allowed.

As far as the algorithm constraint is concerned it is driven by the necessity for the server to insist on accepting specific algorithms, i.e, it is not the client which chooses how to validate the token with which algorithm, but the server.

In smallrye-jwt you can workaround it by creating an instance of  [JWTParser](https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java), see the [tests](https://github.com/smallrye/smallrye-jwt/blob/main/testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java), you'd need to check the current token's `alg` header (convert Base64 URL decoded first part of the token sequence split by `.`), and then use the parser to validate.

Please experiment and let me know how it goes.

**Comment by SamyLegal** [comment]
Hi,

Thanks for your feedback.

I managed to validate different Jwts created from different algorithms by creating a specific factory extending the JWTCallerPrincipalFactory class.

I decode the token beforehand as you indicated to me and define the algorithm according to that indicated in the Jwt.

Here is the code in my project with explanation.

```java
package fr.mgdis.authentication;

import io.smallrye.jwt.algorithm.SignatureAlgorithm;
import io.smallrye.jwt.auth.principal.*;
import jakarta.annotation.Priority;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Alternative;
import org.apache.commons.codec.binary.Base64;
import org.jose4j.jwt.consumer.JwtContext;
import org.json.JSONObject;

/**
 * By default, the "smallrye-jwt" library verifies the algorithm used to create the key from the value defined
 * in the "mp.jwt.verify.publickey.algorithm" property.
 * The problem is that we can only define one algorithm whereas if we have a Json Web KeySet
 * with two different algorithms this does not work because the algorithm does not correspond
 * to the one defined at the property level.
 * The library does not trust the "alg" property present in the header of a jwt.
 * To get around this problem, we use a specific factory in order to be able to change the authorized
 * algorithm to create the key from the value of the algorithm defined in the Jwt.
 */
@ApplicationScoped
@Alternative
@Priority(1)
public class MGJWTCallerPrincipalFactory extends JWTCallerPrincipalFactory {

  private final DefaultJWTTokenParser parser = new DefaultJWTTokenParser();

  @Override
  public JWTCallerPrincipal parse(String token, JWTAuthContextInfo authContextInfo) throws ParseException {
    // Extract algorithm use for build the Jwt
    String[] tokenHeader = token.split("\\.");
    JSONObject header = new JSONObject(new String(Base64.decodeBase64(tokenHeader[0].getBytes())));

    // Set the signature algorithm
    authContextInfo.setSignatureAlgorithm(header.get("alg").toString().equalsIgnoreCase("HS256") ? SignatureAlgorithm.HS256 : SignatureAlgorithm.RS256);

    JwtContext jwtContext = parser.parse(token, authContextInfo);
    String type = jwtContext.getJoseObjects().get(0).getHeader("typ");
    return new DefaultJWTCallerPrincipal(type, jwtContext.getJwtClaims());
  }
}
```

What do you think ?

**Comment by sberyozkin** [comment]
@SamyLegal It looks like a very neat solution, without having all of this code visible to the endpoint code itself.  It might sense to create a new instance of JWTAuthContextInfo copy initialized with `authContextInfo` and reset the algorithm on this new instance, to stress the default config is being overridden, though it is a minor/subjective detail

**Comment by SamyLegal** [comment]
I note the creation of a JWTAuthContextInfo instance as an evolution.

Thanks for the answers.

I close the issue having found a solution to my problem.

THANKS
