### ISSUE TITLE
Add KeyEncryptionAlgorithm "dir" enum value

### ISSUE THREAD

**Issue by vickymicky** [smallrye/smallrye-jwt#734]
At the moment, there is no support for, key encryption algorithm -> "Direct use of a shared symmetric key as the CEK" (dir)
https://datatracker.ietf.org/doc/html/rfc7518#section-4.7

**Comment by sberyozkin** [comment]
I agree, I've been contemplating to introduce it after noticing Auth0 access tokens, when encrypted, use the `dir` algorithm
