### ISSUE TITLE
allow multiple signature algorithms

### ISSUE THREAD

**Issue by Dieken** [smallrye/smallrye-jwt#754]
https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L224

```java
    @Inject
    @ConfigProperty(name = "mp.jwt.verify.publickey.algorithm")
    private Optional<SignatureAlgorithm> mpJwtPublicKeyAlgorithm;
```

This should be `Optional<Set<SignatureAlgorithm>> mpJwtPublicKeyAlgorithms`,  so that JWT tokens can smoothly switch to another algorithm.

**Comment by sberyozkin** [comment]
To be fixed for 4.4.4
