### ISSUE TITLE
JWTCallerPrincipalFactory is instantiated each time if not explicitly set

### ISSUE THREAD

**Issue by hdepalma** [smallrye/smallrye-jwt#765]
When the instantiation of the JWTCallerPrincipalFactory is not externally managed (i.e. when using io.smallrye.jwt.auth.principal.DefaultJWTParser#DefaultJWTParser(io.smallrye.jwt.auth.principal.JWTAuthContextInfo) ), it is instantiated each time a token is parsed.

This causes the JWK sets to never be cached and a call to the OIDC provider is always made to retrieve them. Implicitely, it has a huge impact on performances.
Just making the factory producer RequestScoped (or using a ThreadLocal when not using CDI) has a huge performance improvement, without any concurrency risk.

Was it a deliberate choice?

**Comment by sberyozkin** [comment]
@hdepalma Can you please prototype the impacted application code, do you mean `@Inject JWTParser parser;` ?

**Comment by hdepalma** [comment]
Sure, thanks for replying.

We use smallrye-jwt version 3.4.0 and are not using CDI to instantiate our parser.

In order to parse our token (for each request), we create an instance of a JWTParser using:
``final JWTParser parser = new DefaultJWTParser(jwtAuthContextInfo);``
This will then obtain a JWTCallerPrincipalFactory by calling
``new JWTCallerPrincipalFactoryProducer().getFactory()``

Because the producer is created each time, a new factory is instantiated at each request (``JWTCallerPrincipalFactory.instance()``), causing the cache to not be populated and JWK sets to be requested each time.

**Comment by sberyozkin** [comment]
@hdepalma Having `@Inject JWTParser parser;` is thread safe, is there a reason why you don't use this option ?

**Comment by hdepalma** [comment]
@sberyozkin, in our implementation the class using the parser is not a CDI bean and as the library offers the ability to explicitely instantiate a parser, it appeared straight forward to use it this way.
Furthermore, we have 2 different auth contexts and hence 2 different parsers. To do that using CDI, we would need to extend the DefaultJWTParser in order to provide the proper JWTAuthContextInfo in each parser (a CDI provider is not of any help here).

**Comment by hdepalma** [comment]
@sberyozkin they are created in a filter, so on every request.
If we can ensure everything is thread safe we can easily change so they are created at init time. For now, we chose a ThreadLocal option as a quick and safe tactical fix, but plan to implement a proper strategic solution.

But the main point of this issue is not about how to solve it but more about why the library offers the ability to create a parser without providing the caller principal factory. It does not mention that this factory would then be created each time and causing the non ability to cache the JWK sets.
It resulted in a huge latency in production, cost us resources to identify the problem and implied a re-delivery once fixed.

Should not this constructor be removed? Or at least, should not a comment be added to warn about this flaw when using it?

**Comment by sberyozkin** [comment]
@hdepalma No, if you are deciding to create a parser instance dynamically per request then it is the application's responsibility to manage these parsers. The more I read into it the more I think it is an application setup issue.
If you have 2 different parsers per different requests path, then consider binding individual filters to specific paths, for example, with the JAX-RS `DynamicFeature` and have the parser created once at this filter's init time, and this is it.

I believe now this issue is invalid

**Comment by hdepalma** [comment]
@sberyozkin I totally understand your point and I agree with it, but I am not sure you understand mine.

Nothing prevents nor warns about using the library the way we use it. Nothing tells you if a parser is thread safe and can be instantiated at init time. You know it, we do not.
Also in regards to
>  it is the application's responsibility to manage these parsers. The more I read into it the more I think it is an application setup issue.
I totally agree, but then the instantiation of the JWTCallerPrincipalFactory should also be left to the application itself and calling [DefaultJWTParser(JWTAuthContextInfo authContextInfo)](https://github.com/smallrye/smallrye-jwt/blob/3.4.0/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java#L50) should be prohibited to avoid unforeseen issues.

Finally, we cannot have 2 different filters as we answer 2 different parsing for the same path (external and internal tokens). But once again that's not the object of this issue, we can make it work (and have done it). I just wanted to prevent any other consumers of the library to encounter the same issues we had.

Happy for you to close the issue if you feel not appropriate, though I still think adding more comments in the code would have clarified things.

Thanks anyway for your time and replies.

**Comment by sberyozkin** [comment]
@hdepalma But users can use that constructor to manage the local PEM key verification. Also this constructor would work for the remote JWKs acquisition and refresh if it is done once. In general, when a constructor is used explicitly no other option but instantiate other required pieces like the factory is available, I'm not sure why did you expect the factory would be managed differently in this case. 

Would you like to open a PR which simply adds JavaDocs to these constructors, adding a note for the one we are talking about that in this case a new factory instance is created ? I don't recall us suggesting to use these constructors in the guide but adding JavaDocs would be useful in any case

**Comment by hdepalma** [comment]
@sberyozkin they are fair points. Your sentence
> Also this constructor would work for the remote JWKs acquisition and refresh if it is done once.

is exactly the point of my concern: how to use the library as it is supposed to be, and what we did not do mainly because it does not mentioned / advised explicitly to do so.

Will try and push a PR with some comments on this.

Thanks again.

**Comment by sberyozkin** [comment]
@hdepalma There is another constructor there accepting the factory too, so, if one sees a constructor which accepts no factory, why is the expectation that this factory will be injected into the instance ? It is technically impossible if one drives the parser instantiation directly.

But in any case, I think we are in agreement that JavaDocs should be there clarifying things
