### ISSUE TITLE
Respect `smallrye.jwt.path.groups` even if the `groups` claim is present in the token

### ISSUE THREAD

**Issue by oemel09** [smallrye/smallrye-jwt#766]
When the JWT token has a `groups` claim, it will be used, no matter what the value of `smallrye.jwt.path.groups` is.
If the groups claim contains integers (and not strings), a warning is logged and the groups list is empty.
E. g. in such cases it would be great to honor the `smallrye.jwt.path.groups` property and overwrite the actual groups.

The current implementation works as described in the docs:
> This property can be used if a token has no 'groups' claim but has the groups set in a different claim.

But I'd like to use another claim for the groups, even if groups are already present in the token. Is there any other config I'm overlooking?

**Comment by sberyozkin** [comment]
@oemel09 I think you are right, `smallrye.jwt.path.groups` should take the priority

**Comment by oemel09** [comment]
Nice! I created a PR to tackle this https://github.com/smallrye/smallrye-jwt/pull/767
