### ISSUE TITLE
Sonar plugin issue

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#777]
https://github.com/smallrye/smallrye-jwt/commit/66c409326321b1aceb3e8bd7567e2945994eb8be

failed with

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar (default-cli) on project smallrye-jwt-parent: The plugin [java] does not support Java 11.0.22: org/sonar/plugins/java/JavaPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 -> [Help 1]
```

@radcortez Hi Roberto, do you think we can do something about it, does it matter at all ? I'm assuming the actual release succeeded but I'm not 100% sure

**Comment by MikeEdgar** [comment]
Sonar has removed Java 11 support (for the analyzer). Try bumping this to 17 or 21:
https://github.com/smallrye/smallrye-jwt/blob/main/.github/workflows/build.yml#L79

**Comment by MikeEdgar** [comment]
`sonar.login` should also change to `sonar.token` for newer versions:
https://github.com/smallrye/smallrye-jwt/blob/main/.github/workflows/build.yml#L85

**Comment by sberyozkin** [comment]
Thanks @MikeEdgar Who can change the token, Roberto ? I see it can be changed in the settings but where can I find its value ?

**Comment by MikeEdgar** [comment]
@sberyozkin , it's the same value, just the name of the property has changed.
