### ISSUE TITLE
Optimize the utility code for setting and calculating the path properties

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#84]
Right now `SmallryeJwtUtils` has a nearly identical code for setting the `sub` and `group` path properties and `DefaultJWTTokenParser` has a nearly identical code for resolving those paths.
In the former case both functions can delegate to the internal one, while in the latter the common function can look for a final segment and let the cast be done in the `sub` and `groups` path code branches

**Comment by sberyozkin** [comment]
@radcortez Are you still OK with doing this minor update ? Np at all if you are busy, I can do it as well, minor effort is required

**Comment by radcortez** [comment]
@sberyozkin sure. if you can wait ill next Monday, I'll do it. (I'll try to make it sooner tomorrow).

**Comment by sberyozkin** [comment]
@radcortez thanks, I've just pinged you because we discussed this refactoring, so I wanted to avoid doing this update if you were already on it. I might as well move some code around in my next PR and I will update you FYI :-)
Cheers

**Comment by sberyozkin** [comment]
@radcortez FYI, https://github.com/smallrye/smallrye-jwt/pull/93/files, I did some tweaks, and minor updates, did not save very much in the parser, but I suspect the casts can be also optimized, may be some other time :-)
thanks

**Comment by radcortez** [comment]
+1 :)
