### ISSUE TITLE
Support for KeyStores for keeping the keys

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#85]
Using keystores is quite likely the most used option in practice

**Comment by sberyozkin** [comment]
As part of this issue I will introduce a key type property which will allow to optimize the key loading further

**Comment by darranl** [comment]
+1 to adding the key type property.  FYI we do have some code within the WildFly Elytron project for detecting the type of a keystore, if there was interest we could move this over to a SmallRye project to make it easier to re-use.

A couple of additional points that may be worth considering.
- Obviously the store itself needs a password to open it, but each entry could also have a different password so if multiple entries are to be used this may need to be represented in the config.
- Once the type can be specified sometimes it is desirable to be able to specify the name of the provider to use although that may be more advanced than required here.

A second piece of code we have in the Elytron project that could likely be moved if there was interest is a KeyStore which can wrap another KeyStore to filter the results - similar to what you would get from a database view of a much larger table.

The reason I mention the latter is there may be a point where users would use say a PKCS#11 store but want to filter the keys to a specific set of aliases.

**Comment by sberyozkin** [comment]
@darranl Hi Darran, thanks for the comments, sorry for as delay,
 
> +1 to adding the key type property

I think it may be better for me to create a separate light-weight PR after all, introducing this property only with only few minor code touches, so that you can review and then we can proceed next.

> FYI we do have some code within the WildFly Elytron project for detecting the type of a keystore, if there was interest we could move this over to a SmallRye project to make it easier to re-use

Sounds interesting. Lets have an initial support first then double check, not sure yet if expecting the users to set the key store type could be enough or not.

> Obviously the store itself needs a password to open it, but each entry could also have a different password so if multiple entries are to be used this may need to be represented in the config

Can we say that access to the public keys only requires an alias ? That way it would work the same way it works for a JWK set, the token `kid` would be used to select a given public key, while the `smallrye.jwt.token.kid` property can be used to select a specific public key only.

> Once the type can be specified sometimes it is desirable to be able to specify the name of the provider to use although that may be more advanced than required here

We can definitely support a little bit later, good idea.

> A second piece of code we have in the Elytron project that could likely be moved if there was interest is a KeyStore which can wrap another KeyStore to filter the results - similar to what you would get from a database view of a much larger table

I'm not sure yet how that would be used, but lets keep this option on the table for sure, we can likely get it in once the basic support is in place, I'll be asking you to review :-)

Thanks

**Comment by darranl** [comment]
[Obviously the store itself needs a password to open it, but each entry could also have a different password so if multiple entries are to be used this may need to be represented in the config

Can we say that access to the public keys only requires an alias ? That way it would work the same way it works for a JWK set, the token kid would be used to select a given public key, while the smallrye.jwt.token.kid property can be used to select a specific public key only.](url)

Actually yes that may need double checking, There is a possibility they may need to be wrapped in an X509Certificate but maybe not - I was thinking about the private keys needing a password but that is not what you are accessing.

**Comment by sberyozkin** [comment]
@darranl may be we will have a key type hint or figure out in the code if it is a cert or no, same way we try a pem certificate now. But for JWT generation API we'd need a private key password so we'll support it in time for sure :-)
