### ISSUE TITLE
Load mp.jwt.verify.publickey.location from current folder

### ISSUE THREAD

**Issue by antoniomacri** [smallrye/smallrye-jwt#96]
As stated in [MP-JWT Spec 1.1](https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/configuration.asciidoc#relative-path), 

> Relative or non-URL paths supplied as the location are resolved in the following order:
>  1. `new File(location)`
>  2. `Thread.currentThread().getContextClassLoader().getResource(location)`

However the first case is not working.

In my `microprofile-config.properties`, I have:
```
mp.jwt.verify.publickey.location=jwk-signature.json
```
If I put `jwk-signature.json` in the current folder and run
```
java -jar target/my-quarkus-runner.jar
```
I get:
```
2019-07-03 11:32:37,006 WARN  [io.sma.jwt.aut.pri.DefaultJWTTokenParser] (executor-thread-1) Token is invalid: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: Failed to load a key from: jwk-signature.json): JsonWebSignature{"alg":"RS256","kid":"..."}->...]
```

**Comment by sberyozkin** [comment]
I'll have a look (I'm not sure the file based resource location really scales).

**Comment by sberyozkin** [comment]
@Ladicek the Thorntail specific code loading from the file: scheme will also be gone after this PR is in
